# =============================================
# Configuración de la aplicación
# =============================================
spring.application.name=company-employees
server.port=8080

# =============================================
# MongoDB Configuration
# =============================================
# NOTA: Reemplaza <db_password> con la contraseña real del usuario 'andres'
spring.data.mongodb.uri=mongodb+srv://andres:ZWuqqMSVmQZeXZ5K@java.nmycqbt.mongodb.net/?appName=java
spring.data.mongodb.database=company_employees_db

# =============================================
# Logging
# =============================================
logging.level.root=INFO
logging.level.com.companyemployees=DEBUG
# Para ver los queries que MongoDB ejecuta internamente:
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.pattern.console=%d{HH:mm:ss} [%-5level] %logger{36} - %msg%n
logging.file.name=logs/company-employees.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n
